// Action types enum
const ENUM_ACTION_TYPES = {
    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    ADDED_MOVIE: "ADDED_MOVIE",
    DELETED_MOVIE: "DELETED_MOVIE",
    EDITED_MOVIE: "EDITED_MOVIE"
}

export default ENUM_ACTION_TYPES