const ENUM_SERVICE_ERROR_TYPE = {
    NETWORK_ERROR: 0,
    PARSE_ERROR: 1,
    UNSUCCESSFUL_RESPONSE: 2
};

const ENUM_SERVICE_STATUS = {
    INIT: 0,
    LOADING: 1,
    SUCCESS: 2,
    ERROR: 3
};

export {
    ENUM_SERVICE_ERROR_TYPE,
    ENUM_SERVICE_STATUS
};